// src/app/auth/reset-password/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import Link from 'next/link';

export default function ResetPasswordPage() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState(false);

  useEffect(() => {
    const code = searchParams.get('code');
    if (!code) {
      setError('ลิงค์รีเซ็ตไม่ถูกต้อง');
    }
  }, [searchParams]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    // Validation
    if (!password || !confirmPassword) {
      setError('กรุณากรอกข้อมูลให้ครบถ้วน');
      setLoading(false);
      return;
    }

    if (password !== confirmPassword) {
      setError('รหัสผ่านใหม่และการยืนยันไม่ตรงกัน');
      setLoading(false);
      return;
    }

    if (password.length < 6) {
      setError('รหัสผ่านต้องมีความยาวอย่างน้อย 6 ตัวอักษร');
      setLoading(false);
      return;
    }

    try {
      const response = await fetch('/api/auth/reset-password', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          code: searchParams.get('code'),
          password,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        setError(data.error || 'เกิดข้อผิดพลาด');
        setLoading(false);
        return;
      }

      setSuccess(true);
      setTimeout(() => {
        router.push('/auth/login');
      }, 2000);
    } catch (err) {
      setError('เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง');
      setLoading(false);
    }
  };

  if (success) {
    return (
      <div
        className="min-h-screen py-12 px-4"
        style={{ background: 'linear-gradient(135deg, var(--bg-primary) 0%, var(--bg-secondary) 100%)' }}
      >
        <div className="max-w-md mx-auto">
          <div
            className="rounded-2xl shadow-lg p-8 text-center"
            style={{ borderColor: 'var(--border-light)', background: 'var(--bg-primary)' }}
          >
            <div
              className="w-16 h-16 rounded-full mx-auto mb-4 flex items-center justify-center"
              style={{ background: 'rgba(34, 197, 94, 0.1)' }}
            >
              <span className="text-4xl">✓</span>
            </div>
            <h2 className="text-2xl font-bold mb-2" style={{ color: 'var(--text-primary)' }}>
              เปลี่ยนรหัสผ่านสำเร็จ!
            </h2>
            <p className="text-sm mb-4" style={{ color: 'var(--text-tertiary)' }}>
              กำลังเปลี่ยนเส้นทางไปยังหน้าเข้าสู่ระบบ...
            </p>
            <Link
              href="/auth/login"
              className="inline-block px-6 py-2 rounded-lg font-semibold text-white"
              style={{ background: 'var(--golden)' }}
            >
              เข้าสู่ระบบ
            </Link>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div
      className="min-h-screen py-12 px-4"
      style={{ background: 'linear-gradient(135deg, var(--bg-primary) 0%, var(--bg-secondary) 100%)' }}
    >
      <div className="max-w-md mx-auto">
        <div
          className="rounded-2xl shadow-lg p-8"
          style={{ borderColor: 'var(--border-light)', background: 'var(--bg-primary)' }}
        >
          {/* Header */}
          <div className="mb-8 text-center">
            <h1 className="text-3xl font-bold mb-2" style={{ color: 'var(--text-primary)' }}>
              ตั้งรหัสผ่านใหม่
            </h1>
            <p className="text-sm" style={{ color: 'var(--text-tertiary)' }}>
              ใส่รหัสผ่านใหม่ของคุณ
            </p>
          </div>

          {error && (
            <div
              className="p-4 rounded-lg mb-5"
              style={{
                background: 'rgba(239, 68, 68, 0.1)',
                borderLeft: '4px solid var(--error)',
              }}
            >
              <p style={{ color: 'var(--error)' }} className="text-sm">
                <span className="font-semibold">❌ เกิดข้อผิดพลาด:</span> {error}
              </p>
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-5">
            {/* Password Field */}
            <div>
              <label className="block text-sm font-semibold mb-2" style={{ color: 'var(--text-secondary)' }}>
                รหัสผ่านใหม่
              </label>
              <input
                type="password"
                placeholder="ใส่รหัสผ่านใหม่"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                disabled={loading}
                className="w-full px-4 py-2 rounded-lg border transition-colors focus:outline-none focus:ring-2 focus:ring-[var(--golden)] disabled:opacity-60"
                style={{
                  borderColor: 'var(--border-light)',
                  backgroundColor: '#f9fafb',
                  color: 'var(--text-primary)',
                }}
                required
              />
            </div>

            {/* Confirm Password Field */}
            <div>
              <label className="block text-sm font-semibold mb-2" style={{ color: 'var(--text-secondary)' }}>
                ยืนยันรหัสผ่าน
              </label>
              <input
                type="password"
                placeholder="ยืนยันรหัสผ่าน"
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
                disabled={loading}
                className="w-full px-4 py-2 rounded-lg border transition-colors focus:outline-none focus:ring-2 focus:ring-[var(--golden)] disabled:opacity-60"
                style={{
                  borderColor: 'var(--border-light)',
                  backgroundColor: '#f9fafb',
                  color: 'var(--text-primary)',
                }}
                required
              />
            </div>

            {/* Submit Button */}
            <button
              type="submit"
              disabled={loading}
              className="w-full px-6 py-3 rounded-lg font-semibold text-white transition-all hover:opacity-90 disabled:opacity-60 mt-6"
              style={{
                background: loading ? 'var(--text-tertiary)' : 'var(--golden)',
                color: 'white',
              }}
            >
              {loading ? 'กำลังตั้งรหัสผ่าน...' : 'ตั้งรหัสผ่านใหม่'}
            </button>
          </form>

          {/* Footer */}
          <div className="mt-6 pt-6 border-t text-center" style={{ borderColor: 'var(--border-light)' }}>
            <p className="text-sm" style={{ color: 'var(--text-tertiary)' }}>
              <Link href="/auth/login" className="font-semibold hover:underline" style={{ color: 'var(--golden)' }}>
                เข้าสู่ระบบ
              </Link>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

// src/routes/reset-password/+page.svelte
<script lang="ts">
  import { enhance } from '$app/forms';
  import type { ActionData, PageData } from './$types';

  export let form: ActionData;
  export let data: PageData;

  let loading = false;
  let password = '';
  let confirmPassword = '';
  let showPassword = false;
  let showConfirmPassword = false;
</script>

<div class="max-w-md mx-auto">
  <div class="space-y-6 sm:space-y-8">
    <div class="text-center space-y-2">
      <h1 class="text-3xl sm:text-4xl font-bold text-gray-900 tracking-tight">
        Reset your password
      </h1>
      <p class="text-sm sm:text-base text-gray-600">
        Enter your new password below
      </p>
    </div>

    <div class="bg-white border border-gray-200 rounded-2xl shadow-sm p-6 sm:p-8">
      <form
        method="POST"
        action="?/resetPassword"
        use:enhance={() => {
          loading = true;
          return async ({ update }) => {
            await update();
            loading = false;
          };
        }}
        class="space-y-5"
      >
        {#if form?.error}
          <div class="bg-red-50 border border-red-200 text-red-800 px-4 py-3 rounded-xl text-sm">
            {form.error}
          </div>
        {/if}

        <div class="space-y-2">
          <label for="password" class="block text-sm font-medium text-gray-700">
            New password
          </label>
          <div class="relative">
            <input
              type={showPassword ? 'text' : 'password'}
              id="password"
              name="password"
              bind:value={password}
              required
              minlength="6"
              autocomplete="new-password"
              class="w-full px-4 py-3 pr-12 border border-gray-300 rounded-xl focus:ring-2 focus:ring-gray-900 focus:border-transparent transition-shadow text-sm sm:text-base"
              placeholder="••••••••"
            />
            <button
              type="button"
              on:click={() => showPassword = !showPassword}
              class="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-700 text-sm"
            >
              {showPassword ? 'Hide' : 'Show'}
            </button>
          </div>
          <p class="text-xs text-gray-500">Must be at least 6 characters</p>
        </div>

        <div class="space-y-2">
          <label for="confirmPassword" class="block text-sm font-medium text-gray-700">
            Confirm new password
          </label>
          <div class="relative">
            <input
              type={showConfirmPassword ? 'text' : 'password'}
              id="confirmPassword"
              name="confirmPassword"
              bind:value={confirmPassword}
              required
              minlength="6"
              autocomplete="new-password"
              class="w-full px-4 py-3 pr-12 border border-gray-300 rounded-xl focus:ring-2 focus:ring-gray-900 focus:border-transparent transition-shadow text-sm sm:text-base"
              placeholder="••••••••"
            />
            <button
              type="button"
              on:click={() => showConfirmPassword = !showConfirmPassword}
              class="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-700 text-sm"
            >
              {showConfirmPassword ? 'Hide' : 'Show'}
            </button>
          </div>
        </div>

        <button
          type="submit"
          disabled={loading || password !== confirmPassword || password.length < 6}
          class="w-full bg-gray-900 text-white py-3 px-4 rounded-xl font-medium hover:bg-black transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed shadow-sm hover:shadow-md text-sm sm:text-base min-h-[48px]"
        >
          {loading ? 'Resetting password...' : 'Reset password'}
        </button>
      </form>
    </div>

    <div class="text-center">
      <a
        href="/login"
        class="text-sm text-gray-600 hover:text-gray-900 transition-colors"
      >
        Back to login
      </a>
    </div>
  </div>
</div>
